---
- hosts: all
  tasks:
  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root
  - name: Crontab - Apply Linux Security Updates  
    cron:
      name: "Check Linux Security Updates"
      user: "root"
      minute: 30
      hour: 3
      job: "apt-get install unattended-upgrades"
  - name: Crontab - Apply Ansible Playbook Policies
    cron:
      name: "Ansible Playbook Run"
      user: "root"
      minute: 30
      hour: 3
      job: "ansible-pull -U https://github.com/jeancorreia/ansible-pull-example -i hosts"
